ungdev/UA-front

pages/dashboard/account.js
pages/dashboard/cart.js
pages/dashboard/index.js
pages/dashboard/purchases.js
pages/dashboard/team.js

create new pages
Index
Team
Account
Cart
Purchase

create dashbord routing

---

assets/dashboard.jsx
modules/login.js
modules/loginModal.js
modules/team.js
pages/dashboard/register.css
pages/dashboard/register.js
pages/dashboard/team.css
pages/dashboard/team.js

- Vue non capitaine (aucune action)
- vue capitaine : accepter, refuser nouveau joueur, exclure joueur, désigner chef
- Quitter ou dissoudre son équipe
#25 #24 #26 #32

Gérer son équipe

---

modules/login.js
pages/dashboard/account.css
pages/dashboard/account.js

feat: user can edit his account informations

---

components/Header.css
modules/carts.js
modules/index.js
package.json
pages/_app.css
pages/dashboard/account.css
pages/dashboard/purchases.css
pages/dashboard/purchases.js
pages/dashboard/register.css
pages/dashboard/register.js
pages/dashboard/team.css
pages/dashboard/team.js
yarn.lock

+ update register & team pages style

feat: purchases page

---

components/UI/Helper.css
components/Wrapper.jsx
modules/team.js
pages/dashboard/team.css
pages/dashboard/team.js

- Redirect team/register
- statut team
- champs payé dans team

misc: fixes

---

src/components/UI/LogoSVG.jsx
src/components/UI/LogoSVG.scss
src/components/UI/index.js
src/pages/index.jsx
src/pages/index.scss
src/styles.scss

- Ajout du logo animé sur la page d'accueil

Feat: Animated logo

---

src/pages/_app.jsx

Some meta tags

---

src/pages/dashboard/account.jsx
src/pages/dashboard/account.scss

* Added the link to the Discord authentification
* Rearranged account tab

Added a way to connect to Discord

---

src/modules/login.js
src/pages/dashboard/account.jsx

Je me demande bien pourquoi ces lignes ont disparu de #178... 👼

fix(account): added back route update for patch /users/current

---

src/components/CookieConsent.jsx
src/components/CookieConsent.scss
src/components/UI/Checkbox.jsx
src/components/UI/Checkbox.scss
src/pages/dashboard/shop.jsx
src/pages/dashboard/shop.scss

Un petit peu de scss
*Pour l'instant la checkbox cochée contient une croix mais on peut mettre autre chose*

fix(style): updated style for banner, scoup and checkbox

---

src/components/Tournament.jsx

C'est juste un passage en prod... Franchement, c'est tout

Deploy locked teams count

---

src/pages/dashboard/register.jsx

User now can't join as Coach if Player selected and User can't join as Player if Coach

fix: join team

---

src/pages/legal.jsx

Phone number was not the right one in "préambule" section in the legal page

fix: changed ung's phone number in legal page

---

src/pages/legal.jsx

* fix: changed ung's phone number in legal page

fix: changed ung's phone number in legal page (#235)

---

src/components/SupplementList.jsx
src/modules/index.js
src/modules/items.js
src/pages/dashboard/purchases.jsx
src/pages/dashboard/shop.jsx

Vu qu'on fetch `/items` dans tous les cas, autant utiliser des infos à jour 😉

fix(shop): remove redux

---

src/components/SupplementList.jsx
src/global.scss
src/pages/dashboard/shop.jsx
src/pages/dashboard/shop.scss

Ajoute la possibilité de pouvoir louer du matériel (dans un tableau séparé des autres suppléments)

fix: add support for rent items, fix signup progress bar

---

src/components/UserModal.jsx
src/pages/dashboard/purchases.jsx
src/pages/dashboard/purchases.scss

Petite correction de contenu et ajout du support pour https://github.com/ungdev/UA-api/pull/129

fix: check etupay callbacks

---

src/components/Navbar.jsx

* fix: readded the partners link on the navbar
* update to latest dev branch
* Revert "update to latest dev branch"
This reverts commit 93b22e2618bb13a1efc485d289fa92d3fd5cfb63.
Co-authored-by: Pulpss <puulps@gmail.com>

Fix/partners (#252)

---

src/pages/index.jsx

* fix: readded the partners link on the navbar
* update to latest dev branch
* Revert "update to latest dev branch"
This reverts commit 93b22e2618bb13a1efc485d289fa92d3fd5cfb63.
* fix: uncommented the partners at the bottom of the index page

Fix/partners (#254)

---

Dockerfile
next.config.js
package.json
pnpm-lock.yaml

changed Dockerfile to make Webpack alias available during build process

fix: build

---

src/app/tournaments/content.tsx
src/app/tournaments/style.module.scss

fix: tournaments arrows

---

src/app/event/page.tsx
src/app/help/page.tsx

Typo + some information were incorrect in the FAQ

fix: some informations where incorrect in the FAQ

---

src/app/tournaments/content.tsx
src/app/tournaments/layout.module.scss

When arriving on the /tournaments page, an unfading occured as normal, but then on small screens (width < 1024px), it would fade again, and never unfade

Fix error with fading (#276)

---

src/app/help/page.tsx

12yo to 6yo for the pokémon in the FAQ
Absolutely none

info: changed 12yo to 6yo in the FAQ for pokémon

---

src/components/landing/LoginModal.tsx
src/modules/register.ts

- Added a resend email panel after registering

feat: resendEmail

---

src/app/(dashboard)/layout.tsx
src/modules/login.ts

* register link did not appear in the menu of the dashboard
* there were 2 slashes (/) at the beginnning of the route calls POST and DELETE users/current/spectate
none, they are more like fixing changes :rofl: excuse me

fix: small fixes on dashboard

---

src/app/(dashboard)/dashboard/team/page.tsx
src/app/event/page.tsx
src/app/help/page.tsx

fix: some problems fixed

---

src/app/(dashboard)/dashboard/register/page.tsx
src/app/(dashboard)/dashboard/shop/page.tsx
src/app/(dashboard)/dashboard/team/page.tsx
src/app/help/page.tsx
src/app/page.tsx
src/components/UI/DoubleImage.tsx
src/components/UI/FileInput.tsx
src/components/UI/Input.tsx
src/components/dashboard/AddPlaceModal.tsx
src/components/dashboard/Cart.tsx
src/components/dashboard/PartnerModal.tsx
src/components/dashboard/SupplementList.tsx
src/components/dashboard/UserModal.tsx
src/components/landing/Slider.module.scss
src/utils/uploadLink.ts

Fixes front

---

src/app/reset/[resetToken]/page.tsx
src/app/tournaments/content.tsx
src/app/tournaments/layout-top.tsx
src/components/dashboard/UserModal.tsx

Fix: Minor front updates

---

src/app/event/style.module.scss
src/app/tournaments/layout-top.module.scss
src/app/tournaments/style.module.scss
src/components/UI/FillingBar.module.scss
src/components/dashboard/PanelHeader.module.scss
src/variables.scss

fix: colors

---

src/app/(dashboard)/admin/partners/page.tsx
src/app/(dashboard)/admin/tournaments/page.tsx
src/app/(dashboard)/dashboard/team/page.tsx
src/app/about/page.tsx
src/app/event/style.module.scss
src/app/page.tsx
src/app/tournaments/content.tsx
src/app/tournaments/layout-top.module.scss
src/app/tournaments/style.module.scss
src/components/Partners.module.scss
src/components/Partners.tsx
src/components/UI/DraggableList.module.scss
src/components/UI/DraggableList.stories.tsx
src/components/UI/DraggableList.tsx
src/components/UI/FillingBar.module.scss
src/components/UI/Square.module.scss
src/components/UI/Square.tsx
src/components/UI/index.ts
src/components/dashboard/PanelHeader.module.scss
src/components/dashboard/PartnerModal.tsx
src/components/dashboard/UserModal.tsx
src/modules/admin.ts
src/modules/users.ts
src/types.ts
src/variables.scss

Some more fixes and features, mostly in the admin panel

---

src/app/(dashboard)/dashboard/team/page.tsx
src/app/tournaments/[id]/content.tsx
src/components/dashboard/TournamentModal.tsx
src/modules/admin.ts

* fix: remove edition of tournament player and coach per team
* fix: remove informations about tournaments on the website

Fix/fixes (#312)

---

src/app/tournaments/[id]/content.tsx

fix: content

---

src/app/(dashboard)/admin/users/page.tsx
src/app/(dashboard)/admin/users/style.module.scss

filters are now automatically created from the tournaments we get from the api

fix: tournament filter

---

src/app/(dashboard)/dashboard/team/page.tsx
src/app/tournaments/[id]/content.tsx
src/app/tournaments/layout.module.scss

fix: add back registered count for registered users

---

src/app/(dashboard)/admin/users/page.tsx
src/app/(dashboard)/admin/users/style.module.scss
src/app/(dashboard)/dashboard/team/page.tsx
src/app/tournaments/[id]/content.tsx
src/app/tournaments/layout.module.scss

Fix: add back registred team count for registered users

---

src/app/tournaments/content.tsx
src/app/tournaments/layout-top.tsx

fix: register issue

---

.env.example
src/app/(dashboard)/dashboard/shop/page.tsx
src/app/(dashboard)/dashboard/shop/style.module.scss
src/app/layout.tsx
src/app/legal/page.tsx
src/app/page.tsx
src/utils/environment.ts

Fix CGV text and small other fixes

---

src/app/tournaments/[id]/content.tsx
src/app/tournaments/content.tsx
src/components/dashboard/TournamentModal.module.scss
src/components/dashboard/TournamentModal.tsx

Fix/fixes (#321)

---

src/app/event/page.tsx
src/app/help/page.tsx

fix: accompanist price change

---

src/components/Partners.module.scss
src/components/Partners.tsx
src/components/UI/Square.module.scss
src/components/UI/Square.tsx

fix: partners

---

src/app/event/page.tsx
src/app/event/style.module.scss

content: added content for the program

---

src/components/UI/Square.tsx

fix: repair partner image

---

src/app/event/page.tsx

fix: typo ; checkin -> check-in

---

src/app/(dashboard)/admin/users/page.tsx
src/modules/users.ts
src/types.ts

fix: crash when filter was applied but no permission was checked

---

src/app/reset/[resetToken]/page.tsx
src/app/reset/[resetToken]/style.module.scss

fix: reset password

---

src/app/(dashboard)/admin/genbadge/page.tsx
src/components/dashboard/UserModal.tsx
src/modules/admin.ts
src/types.ts

fix: add customsingle type

---

src/app/(dashboard)/admin/badge/page.tsx
src/app/(dashboard)/admin/genbadge/page.tsx
src/app/(dashboard)/admin/genbadge/style.module.scss
src/app/(dashboard)/layout.tsx
src/components/UI/Input.tsx
src/components/UI/Select.tsx
src/components/dashboard/UserModal.tsx
src/components/landing/TeamMember.tsx
src/modules/admin.ts
src/modules/users.ts
src/types.ts

Fix badge and add badge generator

---

src/app/(dashboard)/admin/badge/page.tsx
src/app/(dashboard)/admin/badge/style.module.scss
src/app/(dashboard)/admin/genbadge/page.tsx
src/components/UI/FileInput.stories.tsx
src/components/UI/FileInput.tsx
src/components/UI/Icon.tsx
src/components/dashboard/Cart.stories.tsx
src/components/dashboard/PartnerModal.tsx
src/components/dashboard/TournamentModal.tsx
src/components/dashboard/UserModal.module.scss
src/components/dashboard/UserModal.tsx
src/components/landing/TeamMember.module.scss
src/components/landing/TeamMember.tsx
src/modules/admin.ts
src/modules/users.ts
src/types.ts
src/utils/api.ts

* feat: added a way to set the default commission in UserModal
* feat: mainCommission is now saved and loaded to and from the api
* fix: add api
* feat: add timeout property
* fix: add a better ux
* feat: change background color
* fix: add a better ux
* fix: cursor
* fix: now setting default preview commission to be the main commission
* fix: build
* fix: crash when user didn't have a main commission
---------

Feat/ux badge (#349)

---

src/components/dashboard/UserModal.tsx

fix: allow back place allocation

---

src/app/(dashboard)/admin/badge/page.tsx

fix: vieux could not upload their photo

---

src/app/(dashboard)/admin/badge/page.tsx
src/components/dashboard/UserModal.tsx
src/modules/users.ts

Fix Vieux Upload

---

src/app/(dashboard)/dashboard/account/page.tsx
src/app/(dashboard)/dashboard/account/style.module.scss

fix: add back ticket

---

src/app/(dashboard)/dashboard/account/page.tsx
src/app/(dashboard)/dashboard/account/style.module.scss

fix: add back ticket (#358)

---

src/components/landing/TeamMember.tsx

fix: i did a little oupsy

---

src/app/help/page.tsx

content: updated question about spectators in faq

---

src/app/(dashboard)/admin/shop/page.tsx
src/components/UI/Button.tsx
src/utils/upload.ts

Fix small bugs on the admin panel

---

src/app/(dashboard)/dashboard/team/page.tsx
src/app/event/page.tsx
src/app/help/page.tsx
src/app/page.tsx
src/app/tournaments/[id]/content.tsx

Solve errors

---

src/app/event/style.module.scss
src/components/Footer.module.scss
src/components/UI/Table.module.scss

quick fix of the feedback of morning

---

LICENSE
src/app/(dashboard)/dashboard/account/page.tsx
src/app/(dashboard)/dashboard/purchases/page.tsx
src/app/(dashboard)/dashboard/shop/page.tsx
src/app/layout.tsx
src/app/legal/page.tsx
src/app/tournaments/[id]/content.tsx
src/app/tournaments/layout.tsx
src/components/Footer.tsx
src/components/Header.tsx
src/components/dashboard/ItemModal.tsx
src/modules/admin.ts
src/utils/environment.ts

fix: replace 2023 with 2024

---

src/components/landing/LoginModal.tsx
src/modules/register.ts

fix: password confirmation was removed if api did not accept account creation

fix: fixes

---

src/app/(dashboard)/admin/users/page.tsx
src/modules/users.ts

feat: add the user.type column

---

src/app/(dashboard)/admin/users/page.tsx
src/modules/register.ts
src/modules/users.ts

Password confirmation bug
Add userType colomn in admin panel

Merge master

---

src/app/(dashboard)/dashboard/account/page.tsx

fix: tickets display issue

---

src/app/page.tsx

fix: 4850 -> 4750

---

src/app/page.tsx

fix: 4850 -> 4750 (#397)

---

src/app/(dashboard)/admin/users/page.tsx
src/app/tournaments/[id]/content.tsx

filling bar always show and add id and discord id in giga recherche

---

src/app/(dashboard)/admin/genbadge/page.tsx
src/app/(dashboard)/admin/genbadge/style.module.scss
src/types.ts

Custom badge can handle a custom commission
New permission / badge : invite (Invité)

Custom badge commission input

---

src/modules/admin.ts

* feat: first step for mail sending
* feat: update mail step progression and add default components
* feat: implement sending email function and General mail sending panel
* fix: handle undefined MailType in sendMails function and add error toast
* feat: add preview option to mail sending functionality
* feat: add MailRecipient component and styling
* feat: refactor mail sending functionality to use sendGeneralMails and update styles
* fix: lint
* Feat/send tickets (#415)
* feat: first step for mail sending
* feat: update mail step progression and add default components
* feat: implement sending email function and General mail sending panel
* fix: handle undefined MailType in sendMails function and add error toast
* feat: add preview option to mail sending functionality
* feat: add …

Feat/send tickets (#418)

---

src/app/(dashboard)/dashboard/shop/page.tsx

fix: show place in shop for spectator

---

src/app/(dashboard)/dashboard/payment/callback/page.tsx
src/app/(dashboard)/dashboard/shop/page.tsx
src/app/(dashboard)/dashboard/shop/style.module.scss

feat: after a payment, ask user to share the event

---

src/components/landing/TeamMember.tsx

Arthur veut pas être notre présidente :(

présidente --> président :(
